//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVPortal.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HrPayrollEntities : DbContext
    {
        public HrPayrollEntities()
            : base("name=HrPayrollEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCVPortalUser> tblCVPortalUsers { get; set; }
        public virtual DbSet<tblDistrict> tblDistricts { get; set; }
        public virtual DbSet<tblApplicantInfo> tblApplicantInfoes { get; set; }
        public virtual DbSet<tblEducationInfo> tblEducationInfoes { get; set; }
        public virtual DbSet<tblEmploymentInfo> tblEmploymentInfoes { get; set; }
        public virtual DbSet<tblTrainingInfo> tblTrainingInfoes { get; set; }
        public virtual DbSet<tblTrainingType> tblTrainingTypes { get; set; }
        public virtual DbSet<tblJobVacancyPost> tblJobVacancyPosts { get; set; }
        public virtual DbSet<tblJobVacancyPostQuestion> tblJobVacancyPostQuestions { get; set; }
        public virtual DbSet<tblAppliedJob> tblAppliedJobs { get; set; }
        public virtual DbSet<tblJobVacancyPostAnswer> tblJobVacancyPostAnswers { get; set; }
    }
}
