//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVPortal.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppliedJob
    {
        public long AppliedJobsId { get; set; }
        public long CVPortalUsersId { get; set; }
        public long ApplicantId { get; set; }
        public long JobVacancyPostId { get; set; }
        public System.DateTime AppliedDate { get; set; }
        public string IsShortListed { get; set; }
    }
}
