//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVPortal.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEducationInfo
    {
        public long EducationInfoId { get; set; }
        public long ApplicantId { get; set; }
        public int EducationLevelId { get; set; }
        public string EducationLevel { get; set; }
        public string NameofExamination { get; set; }
        public string InstituteName { get; set; }
        public decimal DurationYear { get; set; }
        public string Group { get; set; }
        public string CGPADivision { get; set; }
        public decimal CGPAGrade { get; set; }
        public decimal CGPAOutOf { get; set; }
        public string Board { get; set; }
        public int YearOfPass { get; set; }
        public Nullable<long> EUserId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Department { get; set; }
    }
}
