//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVPortal.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmploymentInfo
    {
        public long EmploymentInfoId { get; set; }
        public long ApplicantId { get; set; }
        public string Designation { get; set; }
        public string JobType { get; set; }
        public string Duties { get; set; }
        public string DutiesRelatedToAppliedJob { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string IsContinue { get; set; }
        public string LeavingReason { get; set; }
        public Nullable<long> EUserId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
