//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVPortal.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJobVacancyPostAnswer
    {
        public long JobVacancyPostAnswerId { get; set; }
        public long CVPortalUsersId { get; set; }
        public long ApplicantId { get; set; }
        public long JobVacancyPostId { get; set; }
        public string Answer { get; set; }
        public Nullable<long> EUserId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<long> UpUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public long JobVacancyPostQuestionId { get; set; }
    }
}
