//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVPortal.DBModel
{
    using System;
    using System.Collections.Generic;


    public partial class tblJobVacancyPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblJobVacancyPost()
        {
            this.tblJobVacancyPostQuestions = new HashSet<tblJobVacancyPostQuestion>();
        }
    
        public long JobVacancyPostId { get; set; }
        public long DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public long DesignationId { get; set; }
        public string DesignationTitle { get; set; }
        public int NoOfVacancy { get; set; }
        public decimal ExperienceRequired { get; set; }
        public Nullable<System.DateTime> PostLiveDate { get; set; }
        public Nullable<System.DateTime> PostClosingDate { get; set; }
        public string JobType { get; set; }
        public string AdditionalComment { get; set; }
        public long WorkingPlaceId { get; set; }
        public string WorkingPlaceName { get; set; }
        public long SiteId { get; set; }
        public string SiteName { get; set; }
        public bool IsActive { get; set; }
        public long OrganizationId { get; set; }
        public Nullable<long> EUserId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<long> UpUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJobVacancyPostQuestion> tblJobVacancyPostQuestions { get; set; }
    }
}
