//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVPortal.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJobVacancyPostQuestion
    {
        public long JobVacancyPostQuestionId { get; set; }
        public long JobVacancyPostId { get; set; }
        public string Question { get; set; }
        public string QuestionType { get; set; }
        public bool IsActive { get; set; }
        public long OrganizationId { get; set; }
        public Nullable<long> EUserId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<long> UpUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        
        public virtual tblJobVacancyPost tblJobVacancyPost { get; set; }
    }
}
