//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVPortal.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrainingInfo
    {
        public long TrainingInfoId { get; set; }
        public long ApplicantId { get; set; }
        public string Title { get; set; }
        public string Topic { get; set; }
        public string Institute { get; set; }
        public string Country { get; set; }
        public int Year { get; set; }
        public string Duration { get; set; }
        public Nullable<long> EUserId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
